### ISSUE TITLE
Is there any way to return the response time

### ISSUE THREAD

**Issue by JonathanKnight** [AntonFagerberg/rackla#12]
When I combine calls to different API providers, I need to monitor the response time for each call. Can this be returned in the Rackla response ?

**Comment by AntonFagerberg** [comment]
Yes! There is no built in way, I've toyed with this but I haven't found a clean solution, so you have to do it manually. What you can do is to save the current timestamp at the start of your end-point and place a  `map` in the pipeline (directly after the `request`) and use it to diff the start timestamp  with the current timestamp and appended the result to the response. By doing so, you'll get a unique response time for each response since the anonymous function inside map is called for each response only when the response is available.

Here´s an complete example when working with json:

```elixir
  get "/resp-time" do
    current_millis = fn() ->
      {mega, sec, micro} = :os.timestamp
      (mega*1000000 + sec)*1000 + round(micro/1000)
    end
    
    urls = ["http://date.jsontest.com/", "http://api.openweathermap.org/data/2.5/weather?q=Malmo,se"]
    
    start_time = current_millis.()
  
    urls
    |> request
    |> map(fn(http_response) ->
      
      end_time = current_millis.() - start_time
      
      case http_response do
        {:error, reason} ->
          "HTTP request failed because: #{reason} in time #{end_time}"
        
        ok_response ->
          case Poison.decode(ok_response) do
            {:ok, json_decoded} ->
              Map.put(json_decoded, "response_time", end_time)

            {:error, reason} ->
              "Failed to decode response because: #{inspect(reason)} in time #{end_time}"
          end
      end
    end)
    |> response(json: true)
  end
```

Hope that suits your needs, let me know otherwise and I'll try to help further!

**Comment by JonathanKnight** [comment]
That is perfect - thank you - and thanks for the framework

**Comment by AntonFagerberg** [comment]
Glad to help!
