### ISSUE TITLE
Caching setup

### ISSUE THREAD

**Issue by beno** [AntonFagerberg/rackla#22]
Hi,

I have been playing around with various integrations of a caching solution (cachex) into my gateway, and of course I can get it to work in several ways, but none of them are very elegant. I was just wondering if you had some advise/ideas on how to do this?

Thanks,
Michel

**Comment by AntonFagerberg** [comment]
I think that utilizing [Plug.Builder](https://hexdocs.pm/plug/Plug.Builder.html) is generally the way to go. You could for example define two cache functions, one which should be invoked before the normal router code and one which should be invoked afterwards.

By doing so you will separate your caching code from the actual end-point code in the router.

Pseudo-code for one of the cache functions: look if there is a cache entry present - if so, return that item and halt, otherwise pass conn to the next plug which will invoke the normal `get` or whatever.

```elixir
defmodule MyApp do
  use Plug.Router
  use Plug.Builder
  
  import Rackla

  plug :check_cache
  plug :match
  plug :dispatch

  get "/things" do
    #...
  end

  defp check_cache(conn, opts) do
    if (has_cache_for(conn.some_url_value)) do
      get_cache_item
      |> Rackla.response
      |> halt
    else
      conn # pass along to next plug
    end
  end
end
```

Similarly, you should have a cache function afterwards which will add something to the cache before sending it to the client.

I think this is a clean way of doing it while still giving you a lot of freedom in regards to how you actually want to implement it.

**Comment by beno** [comment]
Thanks for your input. I have solved it slightly differently, but this is helpful still. Closing.
